"""Full-integer (int8) post-training quantization + evaluation + C-array export.

Produces in training/out/:
  asl_fp32.tflite, asl_int8.tflite, model_data.h, model_data.cc, quant_report.json
and copies asl_int8.tflite + labels.txt into the Android app's assets/.
"""
import json
import shutil
import time
from pathlib import Path

import numpy as np
import tensorflow as tf

HERE = Path(__file__).resolve().parent
OUT = HERE / "out"
ASSETS = HERE.parent / "android" / "SignEdge" / "app" / "src" / "main" / "assets"


def to_float(x):
    return (x.astype(np.float32) / 255.0)[..., None]


def convert(model, rep_x):
    fp32 = tf.lite.TFLiteConverter.from_keras_model(model).convert()

    conv = tf.lite.TFLiteConverter.from_keras_model(model)
    conv.optimizations = [tf.lite.Optimize.DEFAULT]

    def rep_data():
        for i in range(0, len(rep_x)):
            yield [to_float(rep_x[i:i + 1])]

    conv.representative_dataset = rep_data
    conv.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    conv.inference_input_type = tf.int8
    conv.inference_output_type = tf.int8
    return fp32, conv.convert()


def evaluate(tflite_bytes, x, y):
    interp = tf.lite.Interpreter(model_content=tflite_bytes)
    interp.allocate_tensors()
    inp, out = interp.get_input_details()[0], interp.get_output_details()[0]
    correct, times = 0, []
    for i in range(len(x)):
        sample = to_float(x[i:i + 1])
        if inp["dtype"] == np.int8:
            s, z = inp["quantization"]
            sample = np.clip(np.round(sample / s + z), -128, 127).astype(np.int8)
        interp.set_tensor(inp["index"], sample)
        t0 = time.perf_counter()
        interp.invoke()
        times.append((time.perf_counter() - t0) * 1000)
        correct += int(interp.get_tensor(out["index"])[0].argmax() == y[i])
    return correct / len(x), float(np.mean(times))


def write_c_array(tflite_bytes):
    """xxd -i style export used by TensorFlow Lite Micro firmware (Task 3)."""
    lines = []
    for i in range(0, len(tflite_bytes), 12):
        chunk = tflite_bytes[i:i + 12]
        lines.append("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    (OUT / "model_data.h").write_text(
        "// Auto-generated by quantize.py - int8 ASL alphabet model for TFLite Micro\n"
        "#ifndef MODEL_DATA_H_\n#define MODEL_DATA_H_\n\n"
        "extern const unsigned char g_model[];\n"
        "extern const unsigned int g_model_len;\n\n"
        "#endif  // MODEL_DATA_H_\n")
    (OUT / "model_data.cc").write_text(
        '#include "model_data.h"\n\n'
        "// Aligned so TFLM can read flatbuffer fields directly from flash.\n"
        "alignas(16) const unsigned char g_model[] = {\n"
        + "\n".join(lines)
        + f"\n}};\nconst unsigned int g_model_len = {len(tflite_bytes)};\n")


def main():
    model = tf.keras.models.load_model(OUT / "asl_fp32.keras")
    test = np.load(OUT / "test_split.npz")
    x_te, y_te = test["x"], test["y"]
    rep_x = np.load(OUT / "rep_split.npz")["x"][:300]

    fp32, int8 = convert(model, rep_x)
    (OUT / "asl_fp32.tflite").write_bytes(fp32)
    (OUT / "asl_int8.tflite").write_bytes(int8)
    write_c_array(int8)

    acc32, ms32 = evaluate(fp32, x_te, y_te)
    acc8, ms8 = evaluate(int8, x_te, y_te)
    keras_kb = (OUT / "asl_fp32.keras").stat().st_size / 1024

    interp = tf.lite.Interpreter(model_content=int8)
    interp.allocate_tensors()
    d_in, d_out = interp.get_input_details()[0], interp.get_output_details()[0]
    report = {
        "params": int(model.count_params()),
        "keras_fp32_kb": round(keras_kb, 1),
        "tflite_fp32_kb": round(len(fp32) / 1024, 1),
        "tflite_int8_kb": round(len(int8) / 1024, 1),
        "size_reduction_x": round(len(fp32) / len(int8), 2),
        "test_acc_fp32": round(acc32, 4),
        "test_acc_int8": round(acc8, 4),
        "pc_latency_fp32_ms": round(ms32, 3),
        "pc_latency_int8_ms": round(ms8, 3),
        "input_quant": {"scale": float(d_in["quantization"][0]), "zero_point": int(d_in["quantization"][1])},
        "output_quant": {"scale": float(d_out["quantization"][0]), "zero_point": int(d_out["quantization"][1])},
        "test_samples": int(len(x_te)),
    }
    json.dump(report, open(OUT / "quant_report.json", "w"), indent=2)

    print("\n| Model | Size (KB) | Test accuracy | PC latency (ms) |")
    print("|---|---|---|---|")
    print(f"| Keras fp32 | {keras_kb:.1f} | - | - |")
    print(f"| TFLite fp32 | {len(fp32)/1024:.1f} | {acc32*100:.2f}% | {ms32:.3f} |")
    print(f"| TFLite int8 | {len(int8)/1024:.1f} | {acc8*100:.2f}% | {ms8:.3f} |")
    print("\n", json.dumps(report, indent=2))

    ASSETS.mkdir(parents=True, exist_ok=True)
    shutil.copy(OUT / "asl_int8.tflite", ASSETS / "asl_int8.tflite")
    shutil.copy(OUT / "labels.txt", ASSETS / "labels.txt")
    print("Copied model + labels to", ASSETS)


if __name__ == "__main__":
    main()
